## Dataset Load

In [3]:
# Import pandas for working with the dataset
import pandas as pd

In [4]:
# Load the Amazon reviews dataset
df = pd.read_csv("../data/raw/amazon_reviews.csv")

# Display the first 5 rows
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
0,0,NaN,4.0,No issues.,2014-07-23,138,0,0,0,0,0.0,0.0
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0

In [5]:
# Check number of rows and columns
print("Dataset shape:", df.shape)

Dataset shape: (4915, 12)

In [6]:
# Display all column names
print("Columns:")
print(df.columns)

Columns:
Index(['Unnamed: 0', 'reviewerName', 'overall', 'reviewText', 'reviewTime',
       'day_diff', 'helpful_yes', 'helpful_no', 'total_vote',
       'score_pos_neg_diff', 'score_average_rating', 'wilson_lower_bound'],
      dtype='str')

In [7]:
# Display information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4915 non-null   int64
 1   reviewerName          4914 non-null   str
 2   overall               4915 non-null   float64
 3   reviewText            4914 non-null   str
 4   reviewTime            4915 non-null   str
 5   day_diff              4915 non-null   int64
 6   helpful_yes           4915 non-null   int64
 7   helpful_no            4915 non-null   int64
 8   total_vote            4915 non-null   int64
 9   score_pos_neg_diff    4915 non-null   int64
 10  score_average_rating  4915 non-null   float64
 11  wilson_lower_bound    4915 non-null   float64
dtypes: float64(3), int64(6), str(3)
memory usage: 460.9 KB

In [8]:
# Count missing values in each column
missing_values = df.isnull().sum()

print("Missing values:")
print(missing_values)

Missing values:
Unnamed: 0              0
reviewerName            1
overall                 0
reviewText              1
reviewTime              0
day_diff                0
helpful_yes             0
helpful_no              0
total_vote              0
score_pos_neg_diff      0
score_average_rating    0
wilson_lower_bound      0
dtype: int64

In [9]:
# Remove rows where reviewText is missing
df = df.dropna(subset=["reviewText"])

# Check missing values again
print("Missing reviewText:", df["reviewText"].isnull().sum())

Missing reviewText: 0

In [10]:
# Display basic statistics for numerical columns
df.describe()

,Unnamed: 0,overall,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
count,4914.000000,4914.000000,4914.000000,4914.000000,4914.000000,4914.000000,4914.000000,4914.000000,4914.000000
mean,2457.474562,4.587505,437.285307,1.310948,0.210216,1.521164,1.100733,0.075348,0.020015
std,1418.736892,0.996929,209.382779,41.623395,4.023689,44.127580,39.371955,0.255949,0.077149
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-130.000000,0.000000,0.000000
25%,1229.250000,5.000000,281.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2457.500000,5.000000,431.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3685.750000,5.000000,601.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,4914.000000,5.000000,1064.000000,1952.000000,183.000000,2020.000000,1884.000000,1.000000,0.957544

In [11]:
# Display all column names clearly
for column in df.columns:
    print(column)

Unnamed: 0
reviewerName
overall
reviewText
reviewTime
day_diff
helpful_yes
helpful_no
total_vote
score_pos_neg_diff
score_average_rating
wilson_lower_bound

In [12]:
# Display the first 5 rows
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
0,0,NaN,4.0,No issues.,2014-07-23,138,0,0,0,0,0.0,0.0
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0

## Step 8 — Important Columns Verify Karna

Hamare project ke liye initially sirf ye 2 columns important hain:

reviewText → customer ka review

overall → rating

Baaki columns abhi ignore karenge.

In [13]:
# Display review text and rating together
print(df[["reviewText", "overall"]].head(10))

                                          reviewText  overall
0                                         No issues.      4.0
1  Purchased this for my device, it worked as adv...      5.0
2  it works as expected. I should have sprung for...      4.0
3  This think has worked out great.Had a diff. br...      5.0
4  Bought it with Retail Packaging, arrived legit...      5.0
5  It's mini storage.  It doesn't do anything els...      5.0
6  I have it in my phone and it never skips a bea...      5.0
7  It's hard to believe how affordable digital ha...      5.0
8  Works in a HTC Rezound.  Was running short of ...      5.0
9  in my galaxy s4, super fast card, and am total...      5.0

In [14]:
# Check the different rating values
print(df["overall"].value_counts().sort_index())

overall
1.0     244
2.0      80
3.0     142
4.0     527
5.0    3921
Name: count, dtype: int64

In [15]:
# Display a few review texts
print(df["reviewText"].head(5).to_string())

0                                           No issues.
1    Purchased this for my device, it worked as adv...
2    it works as expected. I should have sprung for...
3    This think has worked out great.Had a diff. br...
4    Bought it with Retail Packaging, arrived legit...

## Sentiment Labels Banana

Hamare project ko Positive / Negative / Neutral sentiment chahiye, lekin dataset mein directly sentiment column nahi hai.

Isliye hum overall rating ko sentiment mein convert karenge.

Rating	Sentiment

1–2	     Negative

3	     Neutral

4–5	     Positive

In [16]:
# Convert overall ratings into sentiment labels
def get_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"


df["sentiment"] = df["overall"].apply(get_sentiment)

# Display review, rating, and sentiment
df[["reviewText", "overall", "sentiment"]].head(10)

                                          reviewText  overall sentiment
0                                         No issues.      4.0  Positive
1  Purchased this for my device, it worked as adv...      5.0  Positive
2  it works as expected. I should have sprung for...      4.0  Positive
3  This think has worked out great.Had a diff. br...      5.0  Positive
4  Bought it with Retail Packaging, arrived legit...      5.0  Positive
5  It's mini storage.  It doesn't do anything els...      5.0  Positive
6  I have it in my phone and it never skips a bea...      5.0  Positive
7  It's hard to believe how affordable digital ha...      5.0  Positive
8  Works in a HTC Rezound.  Was running short of ...      5.0  Positive
9  in my galaxy s4, super fast card, and am total...      5.0  Positive

In [17]:
print(df["sentiment"].value_counts())

sentiment
Positive    4448
Negative     324
Neutral      142
Name: count, dtype: int64

## Text Cleaning
start NLP Preprocessing

In [18]:
# Import regular expressions for text cleaning
import re


# Function to clean review text
def clean_text(text):

    # Convert text to lowercase
    text = text.lower()

    # Remove punctuation and special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [19]:
# Apply the cleaning function to all reviews
df["cleaned_review"] = df["reviewText"].apply(clean_text)

# Display original and cleaned reviews
df[["reviewText", "cleaned_review"]].head(10)

,reviewText,cleaned_review
0,No issues.,no issues
1,"Purchased this for my device, it worked as adv...",purchased this for my device it worked as adve...
2,it works as expected. I should have sprung for...,it works as expected i should have sprung for ...
3,This think has worked out great.Had a diff. br...,this think has worked out greathad a diff bran...
4,"Bought it with Retail Packaging, arrived legit...",bought it with retail packaging arrived legit ...
5,It's mini storage. It doesn't do anything els...,its mini storage it doesnt do anything else an...
6,I have it in my phone and it never skips a bea...,i have it in my phone and it never skips a bea...
7,It's hard to believe how affordable digital ha...,its hard to believe how affordable digital has...
8,Works in a HTC Rezound. Was running short of ...,works in a htc rezound was running short of sp...
9,"in my galaxy s4, super fast card, and am total...",in my galaxy s4 super fast card and am totally...

## TF-IDF: Text Ko Numbers Mein Convert Karna

In [20]:
# Import TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Convert cleaned reviews into numerical features
X = vectorizer.fit_transform(df["cleaned_review"])

print("TF-IDF shape:", X.shape)

TF-IDF shape: (4914, 11139)

## Sentiment Model
## Train/Test Split

Ab hum Positive / Neutral / Negative sentiment predict karne ke liye dataset ko:

Training data + Testing data

mein divide karenge.

In [22]:
# Import train_test_split for splitting data
from sklearn.model_selection import train_test_split

# Input features
X_text = df["cleaned_review"]

# Target labels
y = df["sentiment"]

# Split data into training and testing sets
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Display the sizes
print("Training samples:", len(X_train_text))
print("Testing samples:", len(X_test_text))

Training samples: 3931
Testing samples: 983

In [23]:
# Import train_test_split for splitting data
from sklearn.model_selection import train_test_split

# Input features
X_text = df["cleaned_review"]

# Target labels
y = df["sentiment"]

# Split data into training and testing sets
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Display the sizes
print("Training samples:", len(X_train_text))
print("Testing samples:", len(X_test_text))

Training samples: 3931
Testing samples: 983

## TF-IDF ko Training Data par Fit Karna

Pehle humne TF-IDF poore dataset par lagaya tha. Ab actual ML model ke liye sahi approach use karenge:

Training reviews

      ↓
TF-IDF learn karega

      ↓
X_train

Testing reviews

      ↓
same TF-IDF apply hoga

      ↓
X_test

In [24]:
# Import TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Learn TF-IDF features from training reviews
X_train = vectorizer.fit_transform(X_train_text)

# Convert testing reviews using the same learned TF-IDF
X_test = vectorizer.transform(X_test_text)

# Display the shapes
print("Training TF-IDF shape:", X_train.shape)
print("Testing TF-IDF shape:", X_test.shape)

Training TF-IDF shape: (3931, 9847)
Testing TF-IDF shape: (983, 9847)

## Train Sentiment Classification Model

Is step mein hum Logistic Regression model train karenge.

Model:
- TF-IDF features (`X_train`) ko input lega.
- Sentiment labels (`y_train`) se seekhega.
- Reviews ko `Positive`, `Negative`, ya `Neutral` classify karna seekhega.

Training ke baad model unseen testing reviews par sentiment predict karega.

In [25]:
# Import Logistic Regression
from sklearn.linear_model import LogisticRegression

# Create the sentiment classification model
sentiment_model = LogisticRegression(
    max_iter=1000
)

# Train the model using training TF-IDF features and sentiment labels
sentiment_model.fit(X_train, y_train)

print("Sentiment model trained successfully.")

Sentiment model trained successfully.

## Step 14 — Predict Sentiment on Test Data

Is step mein hum trained sentiment model ko testing reviews denge.

Model har review ke liye:
- Positive
- Negative
- Neutral

mein se ek sentiment predict karega.

Hum predictions ko `y_pred` mein store karenge.

In [26]:
# Predict sentiment for the testing data
y_pred = sentiment_model.predict(X_test)

# Display the first 10 predictions
print("First 10 predictions:")
print(y_pred[:10])

First 10 predictions:
['Positive' 'Positive' 'Positive' 'Positive' 'Positive' 'Positive'
 'Positive' 'Positive' 'Positive' 'Negative']

## Evaluate Sentiment Classification Model

Is step mein hum model ki predictions ko actual test labels (`y_test`) ke saath compare karenge.

Evaluation metrics:
- Accuracy
- Precision
- Recall
- F1-score

Hum `classification_report` use karenge taake Positive, Negative aur Neutral
classes ki individual performance bhi dekh saken.

Ye code model train karne ke baad uski performance check karne ke liye hai.

In [27]:
# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Display accuracy
print("Accuracy:", accuracy)

# Display precision, recall, and F1-score for each sentiment class
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9226856561546287

Classification Report:
              precision    recall  f1-score   support

    Negative       0.83      0.29      0.43        65
     Neutral       0.00      0.00      0.00        28
    Positive       0.93      1.00      0.96       890

    accuracy                           0.92       983
   macro avg       0.58      0.43      0.46       983
weighted avg       0.89      0.92      0.90       983

d:\AI-Ml_Roadmap\product-review-analyzer\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\AI-Ml_Roadmap\product-review-analyzer\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\AI-Ml_Roadmap\product-review-analyzer\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Step 16 — Prepare Topic Labels

Is step mein hum review text ke liye topic categories define karenge.

Current dataset mein topic labels available nahi hain, isliye hum
keyword-based rules se initial topic labels create karenge.

Initial topics:
- Quality
- Price
- Delivery
- Customer Service
- Packaging
- Other

Ye labels baad mein topic classification model train karne ke liye use honge.

## Step 16.1 — Define Topic Keywords

Hum har topic ke liye relevant keywords define karenge.

Agar review mein kisi topic ke relevant words milte hain,
to review ko us topic ka initial label diya jayega.

Topics:
- Quality
- Price
- Delivery
- Customer Service
- Packaging
- Other

In [28]:
# Define keywords for each topic
topic_keywords = {
    "Quality": [
        "quality", "good", "bad", "excellent", "poor", "durable",
        "broken", "defective"
    ],
    
    "Price": [
        "price", "cost", "cheap", "expensive", "value", "money"
    ],
    
    "Delivery": [
        "delivery", "delivered", "shipping", "ship", "arrived",
        "arrival", "package"
    ],
    
    "Customer Service": [
        "service", "support", "customer", "seller", "refund",
        "response", "help"
    ],
    
    "Packaging": [
        "packaging", "packed", "box", "package", "packing"
    ]
}

# Display the topic keywords
topic_keywords

{'Quality': ['quality',
  'good',
  'bad',
  'excellent',
  'poor',
  'durable',
  'broken',
  'defective'],
 'Price': ['price', 'cost', 'cheap', 'expensive', 'value', 'money'],
 'Delivery': ['delivery',
  'delivered',
  'shipping',
  'ship',
  'arrived',
  'arrival',
  'package'],
 'Customer Service': ['service',
  'support',
  'customer',
  'seller',
  'refund',
  'response',
  'help'],
 'Packaging': ['packaging', 'packed', 'box', 'package', 'packing']}

## Step 16.2 — Create Initial Topic Labels

Is step mein hum defined topic keywords ko reviews par apply karenge.

Har review ke text ko check kiya jayega:
- Agar Quality ke keywords milen → Quality
- Agar Price ke keywords milen → Price
- Agar Delivery ke keywords milen → Delivery
- Agar Customer Service ke keywords milen → Customer Service
- Agar Packaging ke keywords milen → Packaging
- Agar koi match na mile → Other

In labels ko baad mein topic classification model train karne ke liye use kiya jayega.

In [29]:
# Function to assign a topic to a review
def assign_topic(text):
    # Check each topic and its keywords
    for topic, keywords in topic_keywords.items():
        
        # Check whether any keyword exists in the review
        for keyword in keywords:
            if keyword in text:
                return topic
    
    # If no topic keyword is found
    return "Other"


# Apply the topic labeling function to all cleaned reviews
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Display reviews with their assigned topics
df[["cleaned_review", "topic"]].head(10)

                                      cleaned_review    topic
0                                          no issues    Other
1  purchased this for my device it worked as adve...    Other
2  it works as expected i should have sprung for ...    Other
3  this think has worked out greathad a diff bran...    Other
4  bought it with retail packaging arrived legit ...    Price
5  its mini storage it doesnt do anything else an...    Other
6  i have it in my phone and it never skips a bea...  Quality
7  its hard to believe how affordable digital has...    Other
8  works in a htc rezound was running short of sp...    Other
9  in my galaxy s4 super fast card and am totally...    Other

## Step 16.3 — Check Topic Distribution

Is step mein hum count karenge ke keyword-based labeling ke baad
kitne reviews har topic mein assign hue hain.

Isse humein pata chalega ke topics reasonably distributed hain
ya kisi ek topic mein bohat zyada reviews chale gaye hain.

In [30]:
# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the topic distribution
print("Topic Distribution:")
print(topic_counts)

Topic Distribution:
topic
Other               2593
Quality             1223
Price                747
Delivery             169
Customer Service     117
Packaging             65
Name: count, dtype: int64

## Step 16.4 — Improve Topic Keywords

Initial topic distribution mein `Other` bohat zyada tha aur
`Packaging`, `Customer Service`, aur `Delivery` ke examples bohat kam thay.

Is step mein hum topic keywords ko expand karenge taake reviews ko
better topic labels mil saken.

Ye labels rule-based initial labels hain; original dataset ke official
topic labels nahi hain.

In [31]:
# Improve the topic keywords
topic_keywords = {
    "Quality": [
        "quality", "good", "bad", "excellent", "poor",
        "durable", "broken", "defective", "works", "working",
        "works great", "works well", "performance", "reliable"
    ],

    "Price": [
        "price", "cost", "cheap", "expensive",
        "value", "money", "affordable", "worth", "deal"
    ],

    "Delivery": [
        "delivery", "delivered", "shipping", "ship",
        "shipped", "arrived", "arrival", "late",
        "fast shipping", "delivery time"
    ],

    "Customer Service": [
        "service", "support", "customer", "seller",
        "refund", "response", "help", "replacement",
        "return", "contact"
    ],

    "Packaging": [
        "packaging", "packed", "packing", "box",
        "boxed", "package", "wrapped", "unpacked"
    ]
}

# Display the updated keywords
topic_keywords

{'Quality': ['quality',
  'good',
  'bad',
  'excellent',
  'poor',
  'durable',
  'broken',
  'defective',
  'works',
  'working',
  'works great',
  'works well',
  'performance',
  'reliable'],
 'Price': ['price',
  'cost',
  'cheap',
  'expensive',
  'value',
  'money',
  'affordable',
  'worth',
  'deal'],
 'Delivery': ['delivery',
  'delivered',
  'shipping',
  'ship',
  'shipped',
  'arrived',
  'arrival',
  'late',
  'fast shipping',
  'delivery time'],
 'Customer Service': ['service',
  'support',
  'customer',
  'seller',
  'refund',
  'response',
  'help',
  'replacement',
  'return',
  'contact'],
 'Packaging': ['packaging',
  'packed',
  'packing',
  'box',
  'boxed',
  'package',
  'wrapped',
  'unpacked']}

## Step 16.5 — Reassign Topic Labels

Is step mein updated topic keywords ko cleaned reviews par apply karenge.

Har review ko relevant topic assign kiya jayega.
Agar koi keyword match nahi hoga, to review ko `Other` label milega.

In [32]:
# Function to assign a topic to a review
def assign_topic(text):
    # Check each topic and its keywords
    for topic, keywords in topic_keywords.items():
        
        # Check whether any keyword is present in the review
        for keyword in keywords:
            if keyword in text:
                return topic
    
    # Assign Other when no keyword matches
    return "Other"


# Apply the updated topic rules to all reviews
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the updated topic distribution
print("Updated Topic Distribution:")
print(topic_counts)

Updated Topic Distribution:
topic
Quality             2649
Other               1463
Price                533
Customer Service     119
Delivery             102
Packaging             48
Name: count, dtype: int64

## Step 16.6 — Refine Topic Keywords

Previous labeling mein Quality topic ke keywords bohat general thay,
jis ki wajah se bohat zyada reviews Quality mein chale gaye.

Is step mein hum common/general words remove karenge aur
topic-specific keywords use karenge.

Goal:
- Quality ko specific quality-related reviews tak limit karna
- Price, Delivery, Customer Service aur Packaging ko better identify karna
- Unclear reviews ko `Other` mein rakhna

In [33]:
# Refine the topic keywords
topic_keywords = {
    "Quality": [
        "quality", "durable", "defective", "broken",
        "performance", "reliable", "damaged", "faulty"
    ],

    "Price": [
        "price", "cost", "cheap", "expensive",
        "value", "money", "affordable", "worth", "deal"
    ],

    "Delivery": [
        "delivery", "delivered", "shipping", "shipped",
        "arrived", "arrival", "late", "delivery time"
    ],

    "Customer Service": [
        "customer service", "support", "seller",
        "refund", "response", "replacement",
        "return", "contact"
    ],

    "Packaging": [
        "packaging", "packed", "packing",
        "boxed", "wrapped", "unpacked"
    ]
}

# Display the refined keywords
topic_keywords

{'Quality': ['quality',
  'durable',
  'defective',
  'broken',
  'performance',
  'reliable',
  'damaged',
  'faulty'],
 'Price': ['price',
  'cost',
  'cheap',
  'expensive',
  'value',
  'money',
  'affordable',
  'worth',
  'deal'],
 'Delivery': ['delivery',
  'delivered',
  'shipping',
  'shipped',
  'arrived',
  'arrival',
  'late',
  'delivery time'],
 'Customer Service': ['customer service',
  'support',
  'seller',
  'refund',
  'response',
  'replacement',
  'return',
  'contact'],
 'Packaging': ['packaging',
  'packed',
  'packing',
  'boxed',
  'wrapped',
  'unpacked']}

## Step 16.7 — Apply Refined Topic Labels

Is step mein refined topic keywords ko cleaned reviews par apply karenge.

Common/general words ko remove karne ke baad hum check karenge
ke topic distribution ab zyada meaningful hai ya nahi.

In [34]:
# Apply the refined topic labeling rules
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the topic distribution
print("Refined Topic Distribution:")
print(topic_counts)

Refined Topic Distribution:
topic
Other               2761
Price               1130
Quality              633
Delivery             197
Customer Service     147
Packaging             46
Name: count, dtype: int64

## Step 16.6 — Improve Topic Keywords

Previous topic distribution mein `Other` bohat zyada aur `Packaging`
bohat kam tha.

Is step mein hum topic-specific keywords ko expand aur refine karenge.

Hum:
- Quality ke product-condition aur performance words add karenge
- Price ke purchasing/cost related words add karenge
- Delivery ke shipping/arrival related words add karenge
- Customer Service ke return/refund/support words add karenge
- Packaging ke box, wrapping aur package-condition words add karenge

General words ko avoid karenge taake incorrect topic assignments kam hon.

In [35]:
# Improve topic-specific keywords
topic_keywords = {
    "Quality": [
        "quality", "durable", "defective", "broken",
        "performance", "reliable", "faulty", "damaged",
        "defect", "construction", "material", "build",
        "poor quality", "high quality"
    ],

    "Price": [
        "price", "cost", "cheap", "expensive",
        "affordable", "worth it", "overpriced",
        "underpriced", "discount", "sale", "deal"
    ],

    "Delivery": [
        "delivery", "delivered", "shipping", "shipped",
        "arrived", "arrival", "late", "delayed",
        "on time", "delivery time", "delivery date",
        "shipping time", "shipping speed"
    ],

    "Customer Service": [
        "customer service", "customer support",
        "support team", "seller", "refund",
        "replacement", "return", "returned",
        "response", "contacted", "help desk",
        "customer care"
    ],

    "Packaging": [
        "packaging", "package", "packed", "packing",
        "box", "boxed", "wrapping", "wrapped",
        "plastic wrap", "bubble wrap", "sealed",
        "seal", "packaging material", "damaged box",
        "damaged package", "opened package"
    ]
}

# Display the updated keywords
topic_keywords

{'Quality': ['quality',
  'durable',
  'defective',
  'broken',
  'performance',
  'reliable',
  'faulty',
  'damaged',
  'defect',
  'construction',
  'material',
  'build',
  'poor quality',
  'high quality'],
 'Price': ['price',
  'cost',
  'cheap',
  'expensive',
  'affordable',
  'worth it',
  'overpriced',
  'underpriced',
  'discount',
  'sale',
  'deal'],
 'Delivery': ['delivery',
  'delivered',
  'shipping',
  'shipped',
  'arrived',
  'arrival',
  'late',
  'delayed',
  'on time',
  'delivery time',
  'delivery date',
  'shipping time',
  'shipping speed'],
 'Customer Service': ['customer service',
  'customer support',
  'support team',
  'seller',
  'refund',
  'replacement',
  'return',
  'returned',
  'response',
  'contacted',
  'help desk',
  'customer care'],
 'Packaging': ['packaging',
  'package',
  'packed',
  'packing',
  'box',
  'boxed',
  'wrapping',
  'wrapped',
  'plastic wrap',
  'bubble wrap',
  'sealed',
  'seal',
  'packaging material',
  'damaged box',
  'damaged package',
  'opened package']}

## Step 16.7 — Improve Topic Assignment

Previous method mein review ka sirf pehla matching keyword check hota tha.

Ab hum:
1. Har topic ke matching keywords count karenge.
2. Jis topic ke sabse zyada matches honge, woh topic assign hoga.
3. Agar koi keyword match nahi hoga, to `Other` assign hoga.

Is approach se multiple-topic reviews ko better handle kiya ja sakega.

In [36]:
# Function to assign a topic based on the number of matching keywords
def assign_topic(text):
    
    # Store the number of matches for each topic
    topic_scores = {}

    # Check every topic
    for topic, keywords in topic_keywords.items():
        
        # Count matching keywords
        score = 0
        
        for keyword in keywords:
            if keyword in text:
                score += 1
        
        # Save the score for this topic
        topic_scores[topic] = score

    # Find the topic with the highest score
    best_topic = max(topic_scores, key=topic_scores.get)

    # If no keyword matched, assign Other
    if topic_scores[best_topic] == 0:
        return "Other"

    return best_topic


# Apply the improved topic assignment
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the new topic distribution
print("New Topic Distribution:")
print(topic_counts)

New Topic Distribution:
topic
Other               2799
Price               1055
Quality              571
Delivery             220
Customer Service     142
Packaging            127
Name: count, dtype: int64

In [37]:
# Add a new topic for product performance and device compatibility
topic_keywords["Performance / Compatibility"] = [
    "works as expected",
    "works perfectly",
    "works great",
    "works with",
    "compatible",
    "compatibility",
    "performance",
    "speed",
    "read speed",
    "write speed",
    "transfer speed",
    "transfer",
    "device",
    "phone",
    "tablet",
    "computer",
    "laptop",
    "no stuttering",
    "video stuttering"
]

# Display the updated topic list
print("Updated Topics:")
print(list(topic_keywords.keys()))

Updated Topics:
['Quality', 'Price', 'Delivery', 'Customer Service', 'Packaging', 'Performance / Compatibility']

In [38]:
# Remove performance-related phrases from the Quality topic
topic_keywords["Quality"] = [
    "quality",
    "durable",
    "defective",
    "broken",
    "reliable",
    "faulty",
    "damaged",
    "defect",
    "construction",
    "material",
    "build",
    "poor quality",
    "high quality",
    "love this product",
    "great product",
    "excellent product",
    "best product"
]

# Display the cleaned Quality keywords
print("Updated Quality Keywords:")
print(topic_keywords["Quality"])

Updated Quality Keywords:
['quality', 'durable', 'defective', 'broken', 'reliable', 'faulty', 'damaged', 'defect', 'construction', 'material', 'build', 'poor quality', 'high quality', 'love this product', 'great product', 'excellent product', 'best product']

## Recalculate Topic Labels

In [39]:
# Re-assign topics using the updated keyword rules
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the updated topic distribution
print("Updated Topic Distribution:")
print(topic_counts)

Updated Topic Distribution:
topic
Performance / Compatibility    2237
Other                          1081
Price                           807
Quality                         426
Delivery                        164
Customer Service                111
Packaging                        88
Name: count, dtype: int64

## Performance Keywords ko Precise Karna

In [40]:
# Keep only strong performance and compatibility keywords
topic_keywords["Performance / Compatibility"] = [
    "works as expected",
    "works perfectly",
    "works with",
    "compatible with",
    "compatibility",
    "read speed",
    "write speed",
    "transfer speed",
    "transfer rate",
    "high speed",
    "slow speed",
    "fast speed",
    "performance",
    "video stuttering",
    "no stuttering"
]

# Display the refined Performance keywords
print("Refined Performance Keywords:")
print(topic_keywords["Performance / Compatibility"])

Refined Performance Keywords:
['works as expected', 'works perfectly', 'works with', 'compatible with', 'compatibility', 'read speed', 'write speed', 'transfer speed', 'transfer rate', 'high speed', 'slow speed', 'fast speed', 'performance', 'video stuttering', 'no stuttering']

In [41]:
# Re-assign topics using the refined keyword rules
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the final topic distribution
print("Updated Topic Distribution:")
print(topic_counts)

Updated Topic Distribution:
topic
Other                          2460
Price                          1036
Quality                         543
Performance / Compatibility     394
Delivery                        217
Customer Service                140
Packaging                       124
Name: count, dtype: int64

In [42]:
# Re-assign topics using the refined keyword rules
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the final topic distribution
print("Updated Topic Distribution:")
print(topic_counts)

Updated Topic Distribution:
topic
Other                          2460
Price                          1036
Quality                         543
Performance / Compatibility     394
Delivery                        217
Customer Service                140
Packaging                       124
Name: count, dtype: int64

In [43]:
# Check a few example reviews from each topic
for topic in [
    "Price",
    "Quality",
    "Performance / Compatibility",
    "Delivery",
    "Customer Service",
    "Packaging",
    "Other"
]:
    print("\n---", topic, "---")
    
    # Display 5 reviews from the current topic
    print(
        df.loc[
            df["topic"] == topic,
            "cleaned_review"
        ].head(5).to_string(index=False)
    )

--- Price ---
bought it with retail packaging arrived legit i...
i have it in my phone and it never skips a beat...
its hard to believe how affordable digital has ...
solid sdhc card that is fast at reading and wri...
ive been trying for a while to get a hold of a ...

--- Quality ---
this think has worked out greathad a diff bran ...
class 10 speed rating for seamless full hd vide...
sandisk never disappoints as always sandisk pro...
good price works flawless in my samsung s4 norm...
san disk is hard to beat you will pay more for ...

--- Performance / Compatibility ---
it works as expected i should have sprung for t...
i like this sd card because it can take music v...
heard that the cards write speed is insufficien...
the read and write speeds are better than the s...
this works with the nl1520 no video stuttering ...

--- Delivery ---
bought this for my s3 and loaded it with 4 seas...
im amazed i ordered this from amazon on tuesday...
this product arrived in two days prime it was e...
shipped fast and worked really well i use this ...
usual sandisk quality worked as expected and de...

--- Customer Service ---
ordered this for a galaxy s3 lasted a few month...
i used this for a few months in my phone then i...
used it in my galaxy note 2 for the past 16 mon...
had to return this item it would not fit proper...
i bought this card on the strength of the 64gb ...

--- Packaging ---
i bought this to use with my go pro hero 3 blac...
i just received my card it is the class 10 64gb...
used in my phone its plenty fast and works just...
the ultra micro sdhc was fine once i got it wor...
appears to be class 10 holds about as much as i...

--- Other ---
                                         no issues
purchased this for my device it worked as adver...
its mini storage it doesnt do anything else and...
works in a htc rezound was running short of spa...
in my galaxy s4 super fast card and am totally ...

## Strong Topic Rules

Abhi purana assign_topic() replace karte hain.

In [44]:
# Create a new topic assignment function using strong topic phrases
def assign_topic(text):

    # Check Packaging first because packaging words are very specific
    packaging_words = [
        "packaging",
        "retail packaging",
        "bubble wrap",
        "wrapped",
        "sealed",
        "box",
        "boxed"
    ]

    for keyword in packaging_words:
        if keyword in text:
            return "Packaging"

    # Check Delivery
    delivery_words = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "delivery time"
    ]

    for keyword in delivery_words:
        if keyword in text:
            return "Delivery"

    # Check Customer Service
    service_words = [
        "customer service",
        "customer support",
        "support team",
        "refund",
        "replacement",
        "return",
        "seller",
        "contacted"
    ]

    for keyword in service_words:
        if keyword in text:
            return "Customer Service"

    # Check Performance / Compatibility
    performance_words = [
        "works as expected",
        "works perfectly",
        "works with",
        "compatible with",
        "read speed",
        "write speed",
        "transfer speed",
        "high speed",
        "slow speed",
        "fast speed",
        "performance",
        "no stuttering",
        "never skips"
    ]

    for keyword in performance_words:
        if keyword in text:
            return "Performance / Compatibility"

    # Check Price
    price_words = [
        "price",
        "cost",
        "cheap",
        "expensive",
        "affordable",
        "overpriced",
        "discount",
        "sale",
        "deal",
        "value for money"
    ]

    for keyword in price_words:
        if keyword in text:
            return "Price"

    # Check Quality
    quality_words = [
        "quality",
        "durable",
        "defective",
        "broken",
        "reliable",
        "faulty",
        "defect",
        "poor quality",
        "high quality"
    ]

    for keyword in quality_words:
        if keyword in text:
            return "Quality"

    # If no strong topic evidence is found
    return "Other"


print("New topic assignment function created.")

New topic assignment function created.

In [45]:
# Apply the new topic assignment function to all reviews
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display the updated topic distribution
print("Updated Topic Distribution:")
print(topic_counts)

Updated Topic Distribution:
topic
Other                          2628
Price                           909
Performance / Compatibility     518
Quality                         245
Delivery                        240
Packaging                       197
Customer Service                177
Name: count, dtype: int64

In [46]:
# Check sample reviews from each topic
for topic in [
    "Price",
    "Quality",
    "Performance / Compatibility",
    "Delivery",
    "Packaging",
    "Customer Service",
    "Other"
]:
    print("\n---", topic, "---")
    
    # Display 5 reviews from this topic
    print(
        df.loc[
            df["topic"] == topic,
            "cleaned_review"
        ].head(5).to_string(index=False)
    )

--- Price ---
its hard to believe how affordable digital has ...
solid sdhc card that is fast at reading and wri...
good price works flawless in my samsung s4 norm...
ive got a couple of these in varying sizes ive ...
i am very happy with this micro sd i could tell...

--- Quality ---
this think has worked out greathad a diff bran ...
sandisk never disappoints as always sandisk pro...
san disk is hard to beat you will pay more for ...
not much to say other than plug and play good q...
excellent quality excellent speed no complaints...

--- Performance / Compatibility ---
it works as expected i should have sprung for t...
i have it in my phone and it never skips a beat...
heard that the cards write speed is insufficien...
class 10 speed rating for seamless full hd vide...
the read and write speeds are better than the s...

--- Delivery ---
this is just the standard micro sd card i would...
lot of questions about this memory card fitting...
im amazed i ordered this from amazon on tuesday...
this item was priced right and fit right into m...
ive ordered other sd cards before but this one ...

--- Packaging ---
bought it with retail packaging arrived legit i...
i bought this to use with my go pro hero 3 blac...
i just received my card it is the class 10 64gb...
used in my phone its plenty fast and works just...
i got this because i just couldnt pass up the d...

--- Customer Service ---
ordered this for a galaxy s3 lasted a few month...
i used this for a few months in my phone then i...
liked the first one i purchased so much i bough...
does its job and fairly cheap for what its wort...
used it in my galaxy note 2 for the past 16 mon...

--- Other ---
                                         no issues
purchased this for my device it worked as adver...
its mini storage it doesnt do anything else and...
works in a htc rezound was running short of spa...
in my galaxy s4 super fast card and am totally ...

## Step 16.20 — Create Cleaner Topic Rules

Previous keyword rules mein multiple topics overlap kar rahe thay.

Is step mein hum:
- Strong phrases ko priority denge
- General words ko avoid karenge
- Ek review ko uska most relevant topic dene ki koshish karenge

Topics:
- Performance / Compatibility
- Price
- Quality
- Delivery
- Packaging
- Customer Service
- Other

In [47]:
# Cleaner topic assignment function
def assign_topic(text):

    # Performance / Compatibility
    performance_keywords = [
        "write speed",
        "read speed",
        "transfer speed",
        "works as expected",
        "works with",
        "compatible",
        "compatibility",
        "performance",
        "no stuttering",
        "never skips"
    ]

    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"

    # Price
    price_keywords = [
        "good price",
        "great price",
        "affordable",
        "cheap",
        "expensive",
        "overpriced",
        "discount",
        "sale",
        "deal",
        "value for money"
    ]

    for keyword in price_keywords:
        if keyword in text:
            return "Price"

    # Quality
    quality_keywords = [
        "high quality",
        "poor quality",
        "excellent quality",
        "defective",
        "broken",
        "faulty",
        "durable",
        "reliable"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"

    # Delivery
    delivery_keywords = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"

    # Packaging
    packaging_keywords = [
        "packaging",
        "retail packaging",
        "boxed",
        "box",
        "wrapped",
        "sealed"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"

    # Customer Service
    service_keywords = [
        "customer service",
        "customer support",
        "refund",
        "replacement",
        "return",
        "seller"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"

    return "Other"


print("Cleaner topic rules created.")

Cleaner topic rules created.

## Step 16.21 — Apply Cleaner Topic Rules

Is step mein hum new topic assignment function ko
saare reviews par apply karenge.

Phir:
- Topic distribution check karenge
- Dekhenge ke labels reasonable hain ya nahi

In [48]:
# Apply the cleaner topic assignment function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_counts = df["topic"].value_counts()

# Display topic distribution
print("Final Topic Distribution:")
print(topic_counts)

Final Topic Distribution:
topic
Other                          3172
Price                           624
Performance / Compatibility     515
Quality                         215
Delivery                        172
Customer Service                124
Packaging                        92
Name: count, dtype: int64

In [49]:
# Assign a topic to a review using keyword rules
def assign_topic(text):

    # -----------------------------
    # Performance / Compatibility
    # -----------------------------
    performance_keywords = [
        "works as expected",
        "works perfectly",
        "works great",
        "works flawlessly",
        "works with",
        "compatible",
        "compatibility",
        "read speed",
        "write speed",
        "transfer speed",
        "high speed",
        "slow speed",
        "performance",
        "never skips",
        "no stuttering"
    ]

    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"


    # -----------------------------
    # Price
    # -----------------------------
    price_keywords = [
        "price",
        "good price",
        "great price",
        "cost",
        "cheap",
        "expensive",
        "affordable",
        "overpriced",
        "discount",
        "sale",
        "deal",
        "worth it",
        "value for money"
    ]

    for keyword in price_keywords:
        if keyword in text:
            return "Price"


    # -----------------------------
    # Quality
    # -----------------------------
    quality_keywords = [
        "quality",
        "high quality",
        "poor quality",
        "excellent quality",
        "durable",
        "reliable",
        "defective",
        "broken",
        "faulty",
        "defect",
        "damaged",
        "love this product",
        "great product",
        "excellent product",
        "best product",
        "never disappoints"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"


    # -----------------------------
    # Delivery
    # -----------------------------
    delivery_keywords = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "late delivery",
        "fast shipping",
        "shipping time"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"


    # -----------------------------
    # Packaging
    # -----------------------------
    packaging_keywords = [
        "packaging",
        "retail packaging",
        "packed",
        "packing",
        "box",
        "boxed",
        "wrapping",
        "wrapped",
        "bubble wrap",
        "sealed",
        "seal",
        "damaged box",
        "damaged package"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"


    # -----------------------------
    # Customer Service
    # -----------------------------
    service_keywords = [
        "customer service",
        "customer support",
        "support team",
        "seller",
        "refund",
        "replacement",
        "return",
        "returned",
        "response",
        "contacted",
        "customer care"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"


    # -----------------------------
    # No clear topic found
    # -----------------------------
    return "Other"


print("Balanced keyword labeling function created.")

Balanced keyword labeling function created.

In [50]:
# Apply the topic labeling function to every cleaned review
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Display the first 10 reviews with their assigned topics
df[["cleaned_review", "topic"]].head(10)

,cleaned_review,topic
0,no issues,Other
1,purchased this for my device it worked as adve...,Other
2,it works as expected i should have sprung for ...,Performance / Compatibility
3,this think has worked out greathad a diff bran...,Quality
4,bought it with retail packaging arrived legit ...,Price
5,its mini storage it doesnt do anything else an...,Other
6,i have it in my phone and it never skips a bea...,Performance / Compatibility
7,its hard to believe how affordable digital has...,Performance / Compatibility
8,works in a htc rezound was running short of sp...,Other
9,in my galaxy s4 super fast card and am totally...,Other

In [51]:
# Assign a topic to a review using improved keyword rules
def assign_topic(text):

    # -----------------------------
    # 1. Packaging
    # -----------------------------
    packaging_keywords = [
        "retail packaging",
        "bubble wrap",
        "packaging",
        "packing",
        "wrapped",
        "sealed",
        "boxed",
        "damaged box",
        "damaged package"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"


    # -----------------------------
    # 2. Delivery
    # -----------------------------
    delivery_keywords = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "delivery time",
        "shipping time",
        "late delivery"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"


    # -----------------------------
    # 3. Customer Service
    # -----------------------------
    service_keywords = [
        "customer service",
        "customer support",
        "support team",
        "refund",
        "replacement",
        "return",
        "returned",
        "seller",
        "contacted",
        "customer care"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"


    # -----------------------------
    # 4. Performance / Compatibility
    # -----------------------------
    performance_keywords = [
        "works as expected",
        "works as advertised",
        "works perfectly",
        "works great",
        "works flawlessly",
        "works with",
        "works in",
        "works on",
        "compatible",
        "compatibility",
        "fits my",
        "read speed",
        "write speed",
        "reading speed",
        "writing speed",
        "read and write",
        "transfer speed",
        "speed rating",
        "high speed",
        "slow speed",
        "fast speed",
        "super fast",
        "fast card",
        "fast at reading",
        "fast at writing",
        "performance",
        "never skips",
        "no stuttering"
    ]

    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"


    # -----------------------------
    # 5. Price
    # -----------------------------
    price_keywords = [
        "good price",
        "great price",
        "price",
        "cost",
        "cheap",
        "expensive",
        "affordable",
        "overpriced",
        "discount",
        "sale",
        "deal",
        "worth it",
        "value for money"
    ]

    for keyword in price_keywords:
        if keyword in text:
            return "Price"


    # -----------------------------
    # 6. Quality
    # -----------------------------
    quality_keywords = [
        "quality",
        "high quality",
        "poor quality",
        "excellent quality",
        "durable",
        "reliable",
        "defective",
        "broken",
        "faulty",
        "defect",
        "damaged",
        "love this product",
        "great product",
        "excellent product",
        "best product",
        "never disappoints"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"


    # -----------------------------
    # 7. No clear topic
    # -----------------------------
    return "Other"


print("Improved topic labeling function created.")

Improved topic labeling function created.

In [52]:
# Apply the improved topic labeling function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Show some reviews with their new topic labels
df[["cleaned_review", "topic"]].head(10)

,cleaned_review,topic
0,no issues,Other
1,purchased this for my device it worked as adve...,Other
2,it works as expected i should have sprung for ...,Performance / Compatibility
3,this think has worked out greathad a diff bran...,Quality
4,bought it with retail packaging arrived legit ...,Packaging
5,its mini storage it doesnt do anything else an...,Other
6,i have it in my phone and it never skips a bea...,Performance / Compatibility
7,its hard to believe how affordable digital has...,Performance / Compatibility
8,works in a htc rezound was running short of sp...,Performance / Compatibility
9,in my galaxy s4 super fast card and am totally...,Performance / Compatibility

In [53]:
# Check which keywords are matching for row 7
review = df.loc[7, "cleaned_review"]

print("Review:")
print(review)

print("\nPerformance keywords found:")

performance_keywords = [
    "works as expected",
    "works as advertised",
    "works perfectly",
    "works great",
    "works flawlessly",
    "works with",
    "works in",
    "works on",
    "compatible",
    "compatibility",
    "fits my",
    "read speed",
    "write speed",
    "reading speed",
    "writing speed",
    "read and write",
    "transfer speed",
    "speed rating",
    "high speed",
    "slow speed",
    "fast speed",
    "super fast",
    "fast card",
    "fast at reading",
    "fast at writing",
    "performance",
    "never skips",
    "no stuttering"
]

for keyword in performance_keywords:
    if keyword in review:
        print("-", keyword)

print("\nPrice keywords found:")

price_keywords = [
    "good price",
    "great price",
    "price",
    "cost",
    "cheap",
    "expensive",
    "affordable",
    "overpriced",
    "discount",
    "sale",
    "deal",
    "worth it",
    "value for money"
]

for keyword in price_keywords:
    if keyword in review:
        print("-", keyword)

Review:
its hard to believe how affordable digital has become 32 gb in a device one quarter the sie of postage stamp would have been science fiction less than a generation agoi picked this up for portable music when i didnt want to schlep or risk a phone or ipod works great with all sd card readersselect with confidence

Performance keywords found:
- works great

Price keywords found:
- affordable

In [54]:
# Assign one topic to each review using keyword rules
def assign_topic(text):

    # -----------------------------
    # 1. Packaging
    # -----------------------------
    packaging_keywords = [
        "retail packaging",
        "bubble wrap",
        "packaging",
        "packing",
        "wrapped",
        "sealed",
        "boxed",
        "damaged box",
        "damaged package"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"


    # -----------------------------
    # 2. Delivery
    # -----------------------------
    delivery_keywords = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "delivery time",
        "shipping time",
        "late delivery"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"


    # -----------------------------
    # 3. Customer Service
    # -----------------------------
    service_keywords = [
        "customer service",
        "customer support",
        "support team",
        "refund",
        "replacement",
        "return",
        "returned",
        "seller",
        "contacted",
        "customer care"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"


    # -----------------------------
    # 4. Price
    # -----------------------------
    price_keywords = [
        "good price",
        "great price",
        "price",
        "cost",
        "cheap",
        "expensive",
        "affordable",
        "overpriced",
        "discount",
        "sale",
        "deal",
        "worth it",
        "value for money"
    ]

    for keyword in price_keywords:
        if keyword in text:
            return "Price"


    # -----------------------------
    # 5. Performance / Compatibility
    # -----------------------------
    performance_keywords = [
        "works as expected",
        "works as advertised",
        "works perfectly",
        "works great",
        "works flawlessly",
        "works with",
        "works in",
        "works on",
        "compatible",
        "compatibility",
        "fits my",
        "read speed",
        "write speed",
        "reading speed",
        "writing speed",
        "read and write",
        "transfer speed",
        "speed rating",
        "high speed",
        "slow speed",
        "fast speed",
        "super fast",
        "fast card",
        "fast at reading",
        "fast at writing",
        "performance",
        "never skips",
        "no stuttering"
    ]

    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"


    # -----------------------------
    # 6. Quality
    # -----------------------------
    quality_keywords = [
        "quality",
        "high quality",
        "poor quality",
        "excellent quality",
        "durable",
        "reliable",
        "defective",
        "broken",
        "faulty",
        "defect",
        "damaged",
        "love this product",
        "great product",
        "excellent product",
        "best product",
        "never disappoints"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"


    # -----------------------------
    # 7. No clear topic
    # -----------------------------
    return "Other"


print("Final topic labeling function created.")

Final topic labeling function created.

In [55]:
# Apply the final topic labeling function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Display the first 10 reviews with their assigned topics
df[["cleaned_review", "topic"]].head(10)

,cleaned_review,topic
0,no issues,Other
1,purchased this for my device it worked as adve...,Other
2,it works as expected i should have sprung for ...,Performance / Compatibility
3,this think has worked out greathad a diff bran...,Quality
4,bought it with retail packaging arrived legit ...,Packaging
5,its mini storage it doesnt do anything else an...,Other
6,i have it in my phone and it never skips a bea...,Price
7,its hard to believe how affordable digital has...,Price
8,works in a htc rezound was running short of sp...,Performance / Compatibility
9,in my galaxy s4 super fast card and am totally...,Performance / Compatibility

In [56]:
# Check which keywords are matching for row 6
review = df.loc[6, "cleaned_review"]

print("Review:")
print(review)

print("\nPrice keywords found:")

price_keywords = [
    "good price",
    "great price",
    "price",
    "cost",
    "cheap",
    "expensive",
    "affordable",
    "overpriced",
    "discount",
    "sale",
    "deal",
    "worth it",
    "value for money"
]

for keyword in price_keywords:
    if keyword in review:
        print("-", keyword)


print("\nPerformance keywords found:")

performance_keywords = [
    "works as expected",
    "works as advertised",
    "works perfectly",
    "works great",
    "works flawlessly",
    "works with",
    "works in",
    "works on",
    "compatible",
    "compatibility",
    "fits my",
    "read speed",
    "write speed",
    "reading speed",
    "writing speed",
    "read and write",
    "transfer speed",
    "speed rating",
    "high speed",
    "slow speed",
    "fast speed",
    "super fast",
    "fast card",
    "fast at reading",
    "fast at writing",
    "performance",
    "never skips",
    "no stuttering"
]

for keyword in performance_keywords:
    if keyword in review:
        print("-", keyword)

Review:
i have it in my phone and it never skips a beat file transfers are speedy and have not had any corruption issues or memory fade issues as i would expect from the sandisk brand great card to own why entrust your precious files to a slightly cheaper piece of crap if you lose everything can you forgive yourself for not spending the extra couple bucks on a trusted product that goes through good qa

Price keywords found:
- cheap

Performance keywords found:
- never skips

In [57]:
# Refined Price keywords
price_keywords = [
    "good price",
    "great price",
    "affordable",
    "overpriced",
    "value for money",
    "worth the price",
    "worth it",
    "discount",
    "sale",
    "deal"
]

# Refined Performance / Compatibility keywords
performance_keywords = [
    "works as expected",
    "works as advertised",
    "works perfectly",
    "works great",
    "works flawlessly",
    "works with",
    "works in",
    "works on",
    "compatible",
    "compatibility",
    "fits my",
    "read speed",
    "write speed",
    "reading speed",
    "writing speed",
    "read and write",
    "file transfer",
    "file transfers",
    "transfer speed",
    "speed rating",
    "high speed",
    "slow speed",
    "fast speed",
    "super fast",
    "fast card",
    "fast at reading",
    "fast at writing",
    "speedy",
    "performance",
    "never skips",
    "no stuttering"
]

print("Price keywords:", len(price_keywords))
print("Performance keywords:", len(performance_keywords))

Price keywords: 10
Performance keywords: 31

In [58]:
# Assign one topic to each review
def assign_topic(text):

    # -----------------------------
    # 1. Packaging
    # -----------------------------
    packaging_keywords = [
        "retail packaging",
        "bubble wrap",
        "packaging",
        "packing",
        "wrapped",
        "sealed",
        "boxed",
        "damaged box",
        "damaged package"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"


    # -----------------------------
    # 2. Delivery
    # -----------------------------
    delivery_keywords = [
        "delivery",
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "delivery time",
        "shipping time",
        "late delivery"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"


    # -----------------------------
    # 3. Customer Service
    # -----------------------------
    service_keywords = [
        "customer service",
        "customer support",
        "support team",
        "refund",
        "replacement",
        "return",
        "returned",
        "seller",
        "contacted",
        "customer care"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"


    # -----------------------------
    # 4. Price
    # -----------------------------
    for keyword in price_keywords:
        if keyword in text:
            return "Price"


    # -----------------------------
    # 5. Performance / Compatibility
    # -----------------------------
    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"


    # -----------------------------
    # 6. Quality
    # -----------------------------
    quality_keywords = [
        "quality",
        "high quality",
        "poor quality",
        "excellent quality",
        "durable",
        "reliable",
        "defective",
        "broken",
        "faulty",
        "defect",
        "damaged",
        "love this product",
        "great product",
        "excellent product",
        "best product",
        "never disappoints"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"


    # -----------------------------
    # 7. No clear topic
    # -----------------------------
    return "Other"


print("Updated topic function created.")

Updated topic function created.

In [59]:
# Apply the updated topic labeling function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Display the first 10 reviews with their assigned topics
df[["cleaned_review", "topic"]].head(10)

,cleaned_review,topic
0,no issues,Other
1,purchased this for my device it worked as adve...,Other
2,it works as expected i should have sprung for ...,Performance / Compatibility
3,this think has worked out greathad a diff bran...,Quality
4,bought it with retail packaging arrived legit ...,Packaging
5,its mini storage it doesnt do anything else an...,Other
6,i have it in my phone and it never skips a bea...,Performance / Compatibility
7,its hard to believe how affordable digital has...,Price
8,works in a htc rezound was running short of sp...,Performance / Compatibility
9,in my galaxy s4 super fast card and am totally...,Performance / Compatibility

In [60]:
# Count the number of reviews in each topic
topic_distribution = df["topic"].value_counts()

# Display the topic distribution
print("Topic Distribution:")
print(topic_distribution)

Topic Distribution:
topic
Other                          2579
Performance / Compatibility    1008
Price                           444
Quality                         327
Delivery                        246
Customer Service                183
Packaging                       127
Name: count, dtype: int64

In [61]:
# Show 20 reviews that are currently labeled as Other
other_reviews = df[df["topic"] == "Other"]

other_reviews[["cleaned_review", "topic"]].head(20)

                                       cleaned_review  topic
0                                           no issues  Other
1   purchased this for my device it worked as adve...  Other
5   its mini storage it doesnt do anything else an...  Other
10  i like this sd card because it can take music ...  Other
11  it works but file writes are a bit slower than...  Other
12        the name of itself speaks out go sandisk go  Other
16  got this because i had a 2 gb one that filled ...  Other
25  installed in my blackberry q10 sqn1001 and for...  Other
29  as advertised specs match as long as the devic...  Other
30  this item is great i cant believe how small it...  Other
32  i bought 2 of those sandisk 32 gb microsd used...  Other
33  the memory card is an excellent condition and ...  Other
34  ive got a couple of these in varying sizes ive...  Other
35  i only had 8 gigs of memory on my note 2 and w...  Other
36  bought it for my surface pro ive had it in the...  Other
39  using this in a contout gps camera dont waste ...  Other
41  i am very happy with this micro sd i could tel...  Other
42  ive purchased several of these little babies o...  Other
44  more like 8mbs in my note 101 and thats using ...  Other
47  this tiny marvel does what it claims the only ...  Other

In [62]:
# Display the full text of selected Other reviews
selected_rows = [1, 11, 29, 44]

for row in selected_rows:
    print(f"\n--- Row {row} ---")
    print(df.loc[row, "cleaned_review"])

--- Row 1 ---
purchased this for my device it worked as advertised you can never have too much phone memory since i download a lot of stuff this was a no brainer for me

--- Row 11 ---
it works but file writes are a bit slower than expected on a usb3 readeralso both reads and writes are faster with the card inside the standardsize sd adapter 15 mbs vs 10 write 45 mbs vs 22 mbs read on the same card reader cant figure why

--- Row 29 ---
as advertised specs match as long as the device you as using it in can handle it ie usb 30 not some crapple bs it delivers the advertised speed ps the speed is read not write but you knew that right

--- Row 44 ---
more like 8mbs in my note 101 and thats using sandisks own app a bit faster in my note ii but still a disappointment for devices with quad core processors not sure if its the card or the device so benefit of the doubt and four stars

In [63]:
# Add additional technical performance keywords
performance_keywords.extend([
    "file writes",
    "file reads",
    "reads and writes",
    "read and write",
    "mbs",
    "mb/s",
    "specs match",
    "advertised speed",
    "speed"
])

print("Updated Performance keywords:", len(performance_keywords))

Updated Performance keywords: 40

In [64]:
# Re-apply the topic labeling function with the updated keywords
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Check the previously problematic reviews
selected_rows = [1, 11, 29, 44]

for row in selected_rows:
    print(f"\n--- Row {row} ---")
    print("Review:", df.loc[row, "cleaned_review"])
    print("Topic:", df.loc[row, "topic"])

--- Row 1 ---
Review: purchased this for my device it worked as advertised you can never have too much phone memory since i download a lot of stuff this was a no brainer for me
Topic: Other

--- Row 11 ---
Review: it works but file writes are a bit slower than expected on a usb3 readeralso both reads and writes are faster with the card inside the standardsize sd adapter 15 mbs vs 10 write 45 mbs vs 22 mbs read on the same card reader cant figure why
Topic: Performance / Compatibility

--- Row 29 ---
Review: as advertised specs match as long as the device you as using it in can handle it ie usb 30 not some crapple bs it delivers the advertised speed ps the speed is read not write but you knew that right
Topic: Performance / Compatibility

--- Row 44 ---
Review: more like 8mbs in my note 101 and thats using sandisks own app a bit faster in my note ii but still a disappointment for devices with quad core processors not sure if its the card or the device so benefit of the doubt and four stars
Topic: Performance / Compatibility

In [65]:
# Add the past-tense phrase used in the dataset
performance_keywords.append("worked as advertised")

print("Added: worked as advertised")

Added: worked as advertised

In [66]:
# Re-apply the topic label for Row 1
df.loc[1, "topic"] = assign_topic(df.loc[1, "cleaned_review"])

# Display the review and its updated topic
print("Review:")
print(df.loc[1, "cleaned_review"])

print("\nUpdated Topic:")
print(df.loc[1, "topic"])

Review:
purchased this for my device it worked as advertised you can never have too much phone memory since i download a lot of stuff this was a no brainer for me

Updated Topic:
Performance / Compatibility

In [67]:
# Re-apply the updated topic rules to the complete dataset
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Count reviews in each topic
topic_distribution = df["topic"].value_counts()

print("Updated Topic Distribution:")
print(topic_distribution)

Updated Topic Distribution:
topic
Other                          2333
Performance / Compatibility    1289
Price                           444
Quality                         292
Delivery                        246
Customer Service                183
Packaging                       127
Name: count, dtype: int64

In [68]:
# Get reviews that are still labeled as Other
other_reviews = df[df["topic"] == "Other"]

# Display the first 20 Other reviews
other_reviews[["cleaned_review", "topic"]].head(20)

                                       cleaned_review  topic
0                                           no issues  Other
5   its mini storage it doesnt do anything else an...  Other
12        the name of itself speaks out go sandisk go  Other
16  got this because i had a 2 gb one that filled ...  Other
25  installed in my blackberry q10 sqn1001 and for...  Other
30  this item is great i cant believe how small it...  Other
32  i bought 2 of those sandisk 32 gb microsd used...  Other
33  the memory card is an excellent condition and ...  Other
35  i only had 8 gigs of memory on my note 2 and w...  Other
36  bought it for my surface pro ive had it in the...  Other
39  using this in a contout gps camera dont waste ...  Other
41  i am very happy with this micro sd i could tel...  Other
42  ive purchased several of these little babies o...  Other
47  this tiny marvel does what it claims the only ...  Other
48  it does the job and the price was right it cam...  Other
50  a memory card either works or it doesnt this w...  Other
52  upgraded from 32gb to 64gb card for my galaxy ...  Other
53  everything about it was great except for the a...  Other
58  i ordered this for my new samsung galaxy note ...  Other
61  use this in my samsung galaxy s4 have had it f...  Other

In [69]:
# Display full text for selected Other reviews
selected_rows = [25, 35, 36, 48, 50, 53, 61]

for row in selected_rows:
    print(f"\n--- Row {row} ---")
    print(df.loc[row, "cleaned_review"])

--- Row 25 ---
installed in my blackberry q10 sqn1001 and formatted works just fine plenty of storage space for pictures and videos of my son at the park

--- Row 35 ---
i only had 8 gigs of memory on my note 2 and was running out of room now i have so much memory space available i dont know what to do with it

--- Row 36 ---
bought it for my surface pro ive had it in there for a few months and ive had no problems very fast and stable

--- Row 48 ---
it does the job and the price was right it came quickly so im very happy for the purchase i would recommend it and would but it again

--- Row 50 ---
a memory card either works or it doesnt this was always going to be a one star or five star review no middle groundthe adapter is a nice bonus too though i dont think i have anything to use it with

--- Row 53 ---
everything about it was great except for the adapter it was to tight i had to use a tool to take it back out of the adapter causing me to chip it so my fault i guess but i also bought a 16gb version and the adapter for that one was fine

--- Row 61 ---
use this in my samsung galaxy s4 have had it for almost a year now no problems really expands your memory capabilities easy enough to install

In [70]:
performance_keywords.extend([
    "formatted and works",
    "very fast and stable",
    "easy enough to install"
])

price_keywords.append("price was right")

In [71]:
# Reassign topics using the updated keywords
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Show updated topic distribution
print(df["topic"].value_counts())

topic
Other                          2322
Performance / Compatibility    1286
Price                           459
Quality                         291
Delivery                        246
Customer Service                183
Packaging                       127
Name: count, dtype: int64

In [72]:
# Get the reviews that are still labeled as Other
other_reviews = df[df["topic"] == "Other"]

# Display the next 20 Other reviews
other_reviews[["cleaned_review", "topic"]].head(20)

                                       cleaned_review  topic
0                                           no issues  Other
5   its mini storage it doesnt do anything else an...  Other
12        the name of itself speaks out go sandisk go  Other
16  got this because i had a 2 gb one that filled ...  Other
25  installed in my blackberry q10 sqn1001 and for...  Other
30  this item is great i cant believe how small it...  Other
32  i bought 2 of those sandisk 32 gb microsd used...  Other
33  the memory card is an excellent condition and ...  Other
35  i only had 8 gigs of memory on my note 2 and w...  Other
39  using this in a contout gps camera dont waste ...  Other
41  i am very happy with this micro sd i could tel...  Other
42  ive purchased several of these little babies o...  Other
47  this tiny marvel does what it claims the only ...  Other
50  a memory card either works or it doesnt this w...  Other
52  upgraded from 32gb to 64gb card for my galaxy ...  Other
53  everything about it was great except for the a...  Other
58  i ordered this for my new samsung galaxy note ...  Other
65  purchase for hp tablet to have more memory for...  Other
66  can there be anything wrong with a sandisk pro...  Other
68  fast transfer rates i downloaded about 2gb of ...  Other

In [73]:
# Add a specific performance phrase
performance_keywords.append("fast transfer rates")

In [74]:
# Reassign topics using the updated keywords
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Show updated distribution
print(df["topic"].value_counts())

topic
Other                          2321
Performance / Compatibility    1287
Price                           459
Quality                         291
Delivery                        246
Customer Service                183
Packaging                       127
Name: count, dtype: int64

In [75]:
# Get the reviews that are still labeled as Other
other_reviews = df[df["topic"] == "Other"]

# Display the next 20 Other reviews
other_reviews[["cleaned_review", "topic"]].head(20)

                                       cleaned_review  topic
0                                           no issues  Other
5   its mini storage it doesnt do anything else an...  Other
12        the name of itself speaks out go sandisk go  Other
16  got this because i had a 2 gb one that filled ...  Other
25  installed in my blackberry q10 sqn1001 and for...  Other
30  this item is great i cant believe how small it...  Other
32  i bought 2 of those sandisk 32 gb microsd used...  Other
33  the memory card is an excellent condition and ...  Other
35  i only had 8 gigs of memory on my note 2 and w...  Other
39  using this in a contout gps camera dont waste ...  Other
41  i am very happy with this micro sd i could tel...  Other
42  ive purchased several of these little babies o...  Other
47  this tiny marvel does what it claims the only ...  Other
50  a memory card either works or it doesnt this w...  Other
52  upgraded from 32gb to 64gb card for my galaxy ...  Other
53  everything about it was great except for the a...  Other
58  i ordered this for my new samsung galaxy note ...  Other
65  purchase for hp tablet to have more memory for...  Other
66  can there be anything wrong with a sandisk pro...  Other
71  all though it states 16gig it only has 148gig ...  Other

In [76]:
# Display full text for selected Other reviews
selected_rows = [33, 39, 47, 66, 71]

for row in selected_rows:
    print(f"\n--- Row {row} ---")
    print(df.loc[row, "cleaned_review"])

--- Row 33 ---
the memory card is an excellent condition and work as described dependable and easy to use an excellent choice for the enthusiast who requires more storage

--- Row 39 ---
using this in a contout gps camera dont waste your time buying any other brand it will be a waste buy the best to start with

--- Row 47 ---
this tiny marvel does what it claims the only possible problem is that it is so small that you may lose it if you happen to drop it during handling but with 16 gb capacity you wont be handling it often

--- Row 66 ---
can there be anything wrong with a sandisk product the items read to it sooooo quickly i am quite happy

--- Row 71 ---
all though it states 16gig it only has 148gig available but i know that happens and expected it keep this in mind if your wanting more storage you might want to order the 32gig card it was exactly what i expected and needed so no complaints

In [78]:
# Select 10 random reviews from our dataset
# random_state=42 ensures the same 10 reviews appear every time

validation_samples = df.sample(10, random_state=42)

# Display review text and assigned topic
validation_samples[["cleaned_review", "topic"]]

,cleaned_review,topic
2347,this superspeed card works great in my phone i...,Delivery
4344,i purchased this product knowing there might b...,Customer Service
692,bought this to use with my samsung hmx w300 wo...,Performance / Compatibility
3910,this was an inexpensive way to get my galaxy n...,Other
2488,purchased two 32 gbcards for the two new samsu...,Other
79,bought this for my s3 and loaded it with 4 sea...,Other
2603,good scan disk but the wrong one for my camera...,Other
2701,just received this today removed it from the p...,Packaging
2209,what more can i sayim using it to double the m...,Performance / Compatibility
3474,works as advertised no issues to date there ar...,Performance / Compatibility

In [79]:
# Row numbers selected for manual validation
validation_rows = [2347, 4344, 692, 3910, 2488, 79, 2603, 2701, 2209, 3474]

# Display the complete review and its current topic
for row in validation_rows:
    print(f"\n--- Row {row} ---")
    print("Review :", df.loc[row, "cleaned_review"])
    print("Topic  :", df.loc[row, "topic"])

--- Row 2347 ---
Review : this superspeed card works great in my phone i havent had any problems with it since i bought the thing im certainly able to record hd video right onto the card no problem i recommend this for those who need quick data delivery to and from there external card i recommend it
Topic  : Delivery

--- Row 4344 ---
Review : i purchased this product knowing there might be an issue with the galaxy s4 this card worked for a week or two then began to spontaneously unmount and would mount itself back in the unmount periods began to become longer than a few hours days i tried this card in a galaxy note 2 still with the same result i attempted to contact sandisk customer service and utilize the warranty they know of the problem and began the exchange process then instructed me to wait for a mailing label that never came i called back and was told that they would reemail it to me to this day i am still waiting for that email i have never had this issue with this company but with ever changing technology it is what it is right i know this card will be good for some device i have if you own a galaxy phone beware i have not attempted to use this in a samsung tablet so on that i cannot review
Topic  : Customer Service

--- Row 692 ---
Review : bought this to use with my samsung hmx w300 works well good transfer speeds and comes with a normal size sd card to transfer if needed
Topic  : Performance / Compatibility

--- Row 3910 ---
Review : this was an inexpensive way to get my galaxy note ii from 16gb to 32gb of memory its plenty fast and can hold lots of photos music etc
Topic  : Other

--- Row 2488 ---
Review : purchased two 32 gbcards for the two new samsung s4s in or family after using for several weeks no issues at all saving a variety of files photos and office documents
Topic  : Other

--- Row 79 ---
Review : bought this for my s3 and loaded it with 4 seasons of futurama 5 full length hd movies several documentaries and a dozen or so 30 minute comedy shows with plenty of room left over for pictures etconly slight nitpick is when booting up into recovery mode on the s3 it will not recognize the card wanted to update the phone to the latest version of android and it would not see it had to resort to a 2gb microsd i had laying around that wasnt a sd card issue but i thought i would throw that in
Topic  : Other

--- Row 2603 ---
Review : good scan disk but the wrong one for my camera i needed a class 6 this class 10 locks up for no reason and even will lock up my computer when it does
Topic  : Other

--- Row 2701 ---
Review : just received this today removed it from the packaging and inserted it into my samsung galaxy s3 verizon and powered the unit back up and the storage was available no formatting required worked the first time out settings showed 2971gb of total space 32gb version and 2971gb of free space i like the fact that a sd adapter came with it should i ever need to insert the card into my laptop it will come in handy yes i can plug my phone directly to my laptop but if i ever swap this 32gb card out of my phone and replace it with a 64gb version i can use this 32gb version via the adapter for other purposes
Topic  : Packaging

--- Row 2209 ---
Review : what more can i sayim using it to double the memory of my asus tf700 from 32 to 64gb and this card has a good readwrite performance and its sandiskrecommended
Topic  : Performance / Compatibility

--- Row 3474 ---
Review : works as advertised no issues to date there are faster cards out there but you will pay more for them
Topic  : Performance / Compatibility

In [81]:
delivery_keywords.remove("delivery")

NameError: name 'delivery_keywords' is not defined

In [82]:
def assign_topic(text):

    # 1. Packaging
    packaging_keywords = [
        "retail packaging",
        "bubble wrap",
        "packaging",
        "packing",
        "wrapped",
        "sealed",
        "boxed",
        "damaged box",
        "damaged package"
    ]

    for keyword in packaging_keywords:
        if keyword in text:
            return "Packaging"

    # 2. Delivery
    # Removed broad "delivery" because it can mean data transfer
    delivery_keywords = [
        "delivered",
        "shipping",
        "shipped",
        "arrived",
        "arrival",
        "delivery time",
        "shipping time",
        "late delivery"
    ]

    for keyword in delivery_keywords:
        if keyword in text:
            return "Delivery"

    # 3. Customer Service
    service_keywords = [
        "customer service",
        "customer support",
        "support team",
        "refund",
        "replacement",
        "return",
        "returned",
        "seller",
        "contacted",
        "customer care"
    ]

    for keyword in service_keywords:
        if keyword in text:
            return "Customer Service"

    # 4. Price
    for keyword in price_keywords:
        if keyword in text:
            return "Price"

    # 5. Performance / Compatibility
    for keyword in performance_keywords:
        if keyword in text:
            return "Performance / Compatibility"

    # 6. Quality
    quality_keywords = [
        "quality",
        "high quality",
        "poor quality",
        "excellent quality",
        "durable",
        "reliable",
        "defective",
        "broken",
        "faulty",
        "defect",
        "damaged",
        "love this product",
        "great product",
        "excellent product",
        "best product",
        "never disappoints",
        "dependable",
        "excellent choice"
    ]

    for keyword in quality_keywords:
        if keyword in text:
            return "Quality"

    # If no topic keyword is found
    return "Other"

In [83]:
# Apply the updated topic labeling function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Show the updated topic distribution
print(df["topic"].value_counts())

topic
Other                          2322
Performance / Compatibility    1292
Price                           464
Quality                         298
Delivery                        223
Customer Service                188
Packaging                       127
Name: count, dtype: int64

In [84]:
# Check the previously incorrect review
print(df.loc[2347, "cleaned_review"])
print("Topic:", df.loc[2347, "topic"])

this superspeed card works great in my phone i havent had any problems with it since i bought the thing im certainly able to record hd video right onto the card no problem i recommend this for those who need quick data delivery to and from there external card i recommend it
Topic: Performance / Compatibility

In [85]:
# Apply the updated topic labeling function
df["topic"] = df["cleaned_review"].apply(assign_topic)

# Show updated topic distribution
print(df["topic"].value_counts())

topic
Other                          2322
Performance / Compatibility    1292
Price                           464
Quality                         298
Delivery                        223
Customer Service                188
Packaging                       127
Name: count, dtype: int64

In [86]:
# Check Row 2347
print(df.loc[2347, "cleaned_review"])
print("Topic:", df.loc[2347, "topic"])

this superspeed card works great in my phone i havent had any problems with it since i bought the thing im certainly able to record hd video right onto the card no problem i recommend this for those who need quick data delivery to and from there external card i recommend it
Topic: Performance / Compatibility

In [87]:
# Check the remaining validation reviews
remaining_rows = [2701, 2209]

for row in remaining_rows:
    print(f"\n--- Row {row} ---")
    print("Review :", df.loc[row, "cleaned_review"])
    print("Topic  :", df.loc[row, "topic"])

--- Row 2701 ---
Review : just received this today removed it from the packaging and inserted it into my samsung galaxy s3 verizon and powered the unit back up and the storage was available no formatting required worked the first time out settings showed 2971gb of total space 32gb version and 2971gb of free space i like the fact that a sd adapter came with it should i ever need to insert the card into my laptop it will come in handy yes i can plug my phone directly to my laptop but if i ever swap this 32gb card out of my phone and replace it with a 64gb version i can use this 32gb version via the adapter for other purposes
Topic  : Packaging

--- Row 2209 ---
Review : what more can i sayim using it to double the memory of my asus tf700 from 32 to 64gb and this card has a good readwrite performance and its sandiskrecommended
Topic  : Performance / Compatibility

In [88]:
# Check the current topics of all 10 validation rows
validation_rows = [2347, 4344, 692, 3910, 2488, 79, 2603, 2701, 2209, 3474]

for row in validation_rows:
    print(f"Row {row} -> {df.loc[row, 'topic']}")

Row 2347 -> Performance / Compatibility
Row 4344 -> Customer Service
Row 692 -> Performance / Compatibility
Row 3910 -> Other
Row 2488 -> Other
Row 79 -> Other
Row 2603 -> Other
Row 2701 -> Packaging
Row 2209 -> Performance / Compatibility
Row 3474 -> Performance / Compatibility

## Phase 3 — Topic Classification

In this phase, we will train a machine learning model to automatically classify
each product review into a topic.

The topics are:
- Packaging
- Delivery
- Customer Service
- Price
- Performance / Compatibility
- Quality
- Other

We will use TF-IDF to convert review text into numerical features and
Logistic Regression for topic classification.

In [89]:
from sklearn.model_selection import train_test_split

# Review text will be the input
X_topic_text = df["cleaned_review"]

# Topic labels will be the target
y_topic = df["topic"]

# Split the data into training and testing sets
X_topic_train_text, X_topic_test_text, y_topic_train, y_topic_test = train_test_split(
    X_topic_text,
    y_topic,
    test_size=0.2,
    random_state=42,
    stratify=y_topic
)

# Display the number of samples
print("Training samples:", len(X_topic_train_text))
print("Testing samples:", len(X_topic_test_text))

Training samples: 3931
Testing samples: 983

### Step 3.3 — Convert Review Text into TF-IDF Features

Machine learning models cannot directly understand text.

TF-IDF converts each review into numerical features based on the importance
of words in the review dataset.

We will:
- fit TF-IDF on training reviews
- transform training reviews
- transform testing reviews

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create the TF-IDF vectorizer
topic_vectorizer = TfidfVectorizer()

# Learn vocabulary and convert training reviews into TF-IDF features
X_topic_train = topic_vectorizer.fit_transform(X_topic_train_text)

# Convert testing reviews using the same vocabulary
X_topic_test = topic_vectorizer.transform(X_topic_test_text)

# Display the shapes of the feature matrices
print("Training TF-IDF shape:", X_topic_train.shape)
print("Testing TF-IDF shape:", X_topic_test.shape)

Training TF-IDF shape: (3931, 9753)
Testing TF-IDF shape: (983, 9753)

### Step 3.4 — Train the Topic Classification Model

We will use Logistic Regression to learn the relationship between
review text features and their topic labels.

The model will learn patterns from the TF-IDF features and predict
one of our predefined topics for a new review.

In [91]:
from sklearn.linear_model import LogisticRegression

# Create the Logistic Regression topic classification model
topic_model = LogisticRegression(max_iter=1000)

# Train the model using TF-IDF features and topic labels
topic_model.fit(X_topic_train, y_topic_train)

print("Topic classification model trained successfully.")

Topic classification model trained successfully.

### Step 3.5 — Make Topic Predictions

The trained model will now predict topics for the unseen test reviews.

The model will predict one of the predefined topics for each review.

In [92]:
# Predict topics for the test reviews
y_topic_pred = topic_model.predict(X_topic_test)

# Display the first 10 predicted topics
print("Predicted topics:")
print(y_topic_pred[:10])

Predicted topics:
['Other' 'Other' 'Performance / Compatibility' 'Quality'
 'Performance / Compatibility' 'Other' 'Other' 'Other' 'Other' 'Other']

### Step 3.6 — Evaluate the Topic Classification Model

We will evaluate the topic classification model using:

- Accuracy
- Precision
- Recall
- F1-score
- Macro F1-score

These metrics help us understand how well the model predicts each topic.

In [93]:
# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

# Calculate topic classification accuracy
topic_accuracy = accuracy_score(y_topic_test, y_topic_pred)

# Display accuracy
print("Topic Accuracy:", topic_accuracy)

# Display precision, recall, and F1-score for each topic
print("\nTopic Classification Report:")
print(classification_report(y_topic_test, y_topic_pred))

Topic Accuracy: 0.7131230925737538

Topic Classification Report:
                             precision    recall  f1-score   support

           Customer Service       0.60      0.16      0.25        38
                   Delivery       1.00      0.27      0.42        45
                      Other       0.70      0.94      0.80       464
                  Packaging       1.00      0.32      0.48        25
Performance / Compatibility       0.73      0.71      0.72       258
                      Price       0.75      0.42      0.54        93
                    Quality       0.62      0.27      0.37        60

                   accuracy                           0.71       983
                  macro avg       0.77      0.44      0.51       983
               weighted avg       0.72      0.71      0.68       983

### Step 3.7 — Handle Class Imbalance

The topic dataset contains an unequal number of reviews in each topic.

To give smaller classes more importance, we will use
`class_weight="balanced"` in Logistic Regression.

This will help the model pay more attention to underrepresented topics.

In [94]:
from sklearn.linear_model import LogisticRegression

# Create a new Logistic Regression model
# class_weight="balanced" gives more importance to smaller classes
topic_model_balanced = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

# Train the balanced model
topic_model_balanced.fit(
    X_topic_train,
    y_topic_train
)

print("Balanced topic classification model trained successfully.")

Balanced topic classification model trained successfully.

### Step 3.8 — Make Predictions with the Balanced Model

The balanced topic classification model will predict topics
for the unseen test reviews.

We will later compare these predictions with the previous model.

In [95]:
# Predict topics using the balanced model
y_topic_pred_balanced = topic_model_balanced.predict(X_topic_test)

# Display the first 10 predictions
print("Balanced model predictions:")
print(y_topic_pred_balanced[:10])

Balanced model predictions:
['Performance / Compatibility' 'Other' 'Customer Service' 'Quality'
 'Performance / Compatibility' 'Price' 'Other' 'Other' 'Other' 'Delivery']

### Step 3.9 — Evaluate the Balanced Topic Model

We will evaluate the balanced topic classification model using:

- Accuracy
- Precision
- Recall
- F1-score
- Macro F1-score

We will compare these results with the original topic model.

In [96]:
# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report

# Calculate accuracy of the balanced model
balanced_accuracy = accuracy_score(
    y_topic_test,
    y_topic_pred_balanced
)

# Display accuracy
print("Balanced Model Accuracy:", balanced_accuracy)

# Display precision, recall, and F1-score
print("\nBalanced Model Classification Report:")
print(
    classification_report(
        y_topic_test,
        y_topic_pred_balanced
    )
)

Balanced Model Accuracy: 0.7293997965412004

Balanced Model Classification Report:
                             precision    recall  f1-score   support

           Customer Service       0.42      0.74      0.54        38
                   Delivery       0.81      0.76      0.78        45
                      Other       0.88      0.73      0.80       464
                  Packaging       0.77      0.68      0.72        25
Performance / Compatibility       0.71      0.76      0.73       258
                      Price       0.58      0.70      0.63        93
                    Quality       0.50      0.67      0.57        60

                   accuracy                           0.73       983
                  macro avg       0.67      0.72      0.68       983
               weighted avg       0.76      0.73      0.74       983

## Phase 4 — Save Trained Models

We will save the trained sentiment and topic classification models
along with their TF-IDF vectorizers.

These saved files will later be loaded by the FastAPI application.

In [97]:
import joblib
import os

# Create the models folder if it does not already exist
os.makedirs("../models", exist_ok=True)

# Save the sentiment model
joblib.dump(
    sentiment_model,
    "../models/sentiment_model.joblib"
)

# Save the sentiment TF-IDF vectorizer
joblib.dump(
    vectorizer,
    "../models/sentiment_vectorizer.joblib"
)

# Save the balanced topic model
joblib.dump(
    topic_model_balanced,
    "../models/topic_model.joblib"
)

# Save the topic TF-IDF vectorizer
joblib.dump(
    topic_vectorizer,
    "../models/topic_vectorizer.joblib"
)

print("All models and vectorizers saved successfully.")

All models and vectorizers saved successfully.

### Step 4.2 — Verify Saved Models

We will check that all trained models and TF-IDF vectorizers
were successfully saved in the models folder.

In [98]:
import os

# List all files inside the models folder
model_files = os.listdir("../models")

# Display the saved files
print("Saved model files:")

for file in model_files:
    print("-", file)

Saved model files:
- sentiment_model.joblib
- sentiment_vectorizer.joblib
- topic_model.joblib
- topic_vectorizer.joblib